"""0002-Creacion de la tabla posts

Revision ID: 672aad92323a
Revises: 888f14cef4ec
Create Date: 2025-02-01 21:58:29.471911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672aad92323a'
down_revision = '888f14cef4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
