"""0001-Creacion de BD

Revision ID: 888f14cef4ec
Revises: 
Create Date: 2025-02-01 21:25:00.969560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888f14cef4ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
